Adding VBF
LPC-HH/HH4b pull request #98
Opened 2024-04-18 03:54 UTC by dprim7

Added VBF category for multiclass BDT

2024-04-18 13:59 UTC, rkansal47 requested changes
Could you remove the `.ipynb_checkpoints` folders from your commits? And the `.swp` ones.

2024-04-18 14:02 UTC, rkansal47 requested changes

2024-04-18 14:02 UTC, rkansal47 commented on src/HH4b/sensitivity_study/plotting.py
> +import uproot
What is this?

2024-04-18 14:02 UTC, rkansal47 commented on src/HH4b/postprocessing/postprocessing.py
> +=======
This file looks like it wasn't merged properly (has merge conflict markers)

2024-04-20 23:07 UTC, rkansal47 commented
Should we close this in favour of your newer one?

2024-04-21 05:28 UTC, cmantill commented
Closing since Raghav integrated changes in a separate PR

2024-04-21 05:28 UTC, closed without merging